export { default as Home } from "./Home"
export { default as News } from "./News"
export { default as Pics } from "./Pics"
export { default as Vids } from "./Vids"
export { default as Resources } from "./Resources"
export { default as GiftShop } from "./GiftShop"
export { default as LogIn } from "./LogIn"